services:
  - type: web
    name: rag-interview-booking-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_server.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_API_KEY
        value: ""
      - key: QDRANT_URL
        value: ""
      - key: REDIS_URL
        value: "redis://localhost:6379"
      - key: DATABASE_URL
        value: "sqlite:///./app.db"
      - key: PORT
        value: "8000"
    healthCheckPath: /
    autoDeploy: true
    
databases:
  - name: rag-redis
    databaseName: rag_redis
    user: rag_user
    plan: free

# Optional: Add PostgreSQL database instead of SQLite for production
# - name: rag-postgres
#   databaseName: rag_db
#   user: rag_user
#   plan: free